export enum DeliveryModality {
    SUCURSAL = "SUCURSAL",
    OFICINAS = "OFICINAS",
    TERMINAL = "TERMINAL",
    AEREOPUERTO = "AEREOPUERTO",
    DESTINO = "DESTINO",
    TRANSPORTADOR = "TRANSPORTADOR"

}